#!/usr/bin/python
import datetime
import os
import os.path
import shutil

JOURNAL_DIR = os.path.join(os.path.expanduser('~'), 'Dropbox', 'journal')

TEMPLATE_FILE = os.path.join(JOURNAL_DIR, '_template.rst')

def format_date(dt):
    return dt.strftime('%Y-%m-%d')

def get_journal_filename(journal_dir, dt):
    return os.path.join(journal_dir, "{}.rst".format(format_date(dt)))

def open_journal(journal_dir, template_file):
    today = datetime.datetime.now()
    filename_today = get_journal_filename(journal_dir, today)

    if not os.path.exists(filename_today) and os.path.exists(TEMPLATE_FILE):
        shutil.copyfile(template_file, filename_today)

    yesterday = today - datetime.timedelta(days = 1)
    filename_yesterday = get_journal_filename(journal_dir, yesterday)

    os.system("vim {} {} -o".format(filename_today, filename_yesterday))

if __name__ == '__main__':
    open_journal(JOURNAL_DIR, TEMPLATE_FILE)
